version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - tradbot-network

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - FRONTEND_URL=http://localhost:3000
      - AI_SERVICE_URL=http://ai-agent:8001
      - STRATEGY_SERVICE_URL=http://strategy:8002
      - EXECUTION_SERVICE_URL=http://execution:8003
      - MARKET_DATA_SERVICE_URL=http://market-data:8004
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    networks:
      - tradbot-network
    depends_on:
      - ai-agent
      - strategy
      - execution
      - market-data

  # AI Agent Service
  ai-agent:
    build:
      context: ./services/ai-agent
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - FRONTEND_URL=http://localhost:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4
    volumes:
      - ./services/ai-agent:/app
      - /app/node_modules
    networks:
      - tradbot-network

  # Strategy Service
  strategy:
    build:
      context: ./services/strategy
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
      - PORT=8002
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongo:27017/tradbot
    volumes:
      - ./services/strategy:/app
      - /app/node_modules
    networks:
      - tradbot-network
    depends_on:
      - mongo

  # Execution Service
  execution:
    build:
      context: ./services/execution
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
      - PORT=8003
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongo:27017/tradbot
    volumes:
      - ./services/execution:/app
      - /app/node_modules
    networks:
      - tradbot-network
    depends_on:
      - mongo

  # Market Data Service
  market-data:
    build:
      context: ./services/market-data
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
      - PORT=8004
      - FRONTEND_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./services/market-data:/app
      - /app/node_modules
    networks:
      - tradbot-network
    depends_on:
      - redis

  # MongoDB (for storing strategies, user data, etc.)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tradbot-network

  # Redis (for caching market data)
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tradbot-network

volumes:
  mongo-data:
  redis-data:

networks:
  tradbot-network:
    driver: bridge 